### ISSUE TITLE
flake8 + isort

### ISSUE THREAD

**Issue by tetaud-sebastien** [tetaud-sebastien/destination-earth-benchmark#10]
benchmark_cams.py does not pass flake8 test.

`python -m flake8 benchmark_cams.py`

`benchmark_cams.py:14:57: E231 missing whitespace after ','
benchmark_cams.py:30:36: E225 missing whitespace around operator
benchmark_cams.py:31:38: E225 missing whitespace around operator
benchmark_cams.py:32:32: E225 missing whitespace around operator
benchmark_cams.py:33:33: E225 missing whitespace around operator
benchmark_cams.py:34:37: E225 missing whitespace around operator
benchmark_cams.py:41:80: E501 line too long (112 > 79 characters)
benchmark_cams.py:55:1: W293 blank line contains whitespace
benchmark_cams.py:58:38: E225 missing whitespace around operator
benchmark_cams.py:59:40: E225 missing whitespace around operator
benchmark_cams.py:60:34: E225 missing whitespace around operator
benchmark_cams.py:61:35: E225 missing whitespace around operator
benchmark_cams.py:72:35: E231 missing whitespace after ','
benchmark_cams.py:74:36: E231 missing whitespace after ','
benchmark_cams.py:75:32: E231 missing whitespace after ','
benchmark_cams.py:76:80: E501 line too long (86 > 79 charac`

**Comment by KesslerMan** [comment]
Done
