### ISSUE TITLE
Implement decorator

### ISSUE THREAD

**Issue by sebastien-tetaud** [tetaud-sebastien/destination-earth-benchmark#11]
- benchmark_.py should follow the new pipeline architecture via using Decorator.
- The script of the pipeline should be in a function and call in the "if __name__ == "__main__":" 
The strategy has changed for future development with Prefect.

Please refer to the following example:

https://github.com/tetaud-sebastien/destination-earth-benchmark/blob/main/ERA5/benchmark_cds.py

**Comment by KesslerMan** [comment]
Implemented for CAMS.
